- code/stylesheet.dm
- modular_aeiou/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
- vorestation.dme
:cl: Toriate
add: Holy water now has TG-style effects, taking approximately 45 seconds to take effect, and needing a total of about 135 seconds to deconvert cultists
/:cl:
This PR will port TG's holy water effects over. This means that it takes 45 seconds for 10u of holy water to take effect, but ultimately requires 30u of holy water and 135 seconds for a proper deconversion.
As the holy water takes effect, cultists will start stuttering, screaming, and even suffer from seizures. All negative effects are cleared after they are deconverted.
It is possible to remove holy water from someone before they get fully deconverted, however I have not coded in any special interactions for cultist tomes/blades to instantly purge their system of holy water.
Note that the times previously mentioned …
> Ports TG's holywater effects

- code/modules/mob/living/carbon/human/species/station/prometheans_vr.dm
- code/modules/organs/internal/brain.dm
- code/modules/organs/internal/brain_vr.dm
Prometheans will now properly melt into a puddle upon death again.
However, in exchange, they can now be more easily revived, without giving them heavy cloning sickness! Simply inject their core with 40u of phoron, and they'll come back. They may need a few moments to grow back fully, though.
Up for changing anything as needed!
Parity for https://github.com/VOREStation/VOREStation/pull/3750
> Prometheans melt on death, and can now be revived.

- code/modules/mob/living/simple_animal/simple_animal.dm
rsctweak: Re-enables simple animal bonus damage.
/:cl:
Re-enables bonus simpleanimal damage. Pretty much what it says on the tin.
We're aware the map test is failing; as long as the unit test passes we're good.
> Re-enables simple animal damage bonus

- modular_aeiou/code/datums/supplypacks/recreation_aeiou.dm
- vorestation.dme
It compiled after the monkey thing was fixed.
rscadd: You can now buy a crate of air rifles from Cargo, with a very slim chance of getting a Cuban Pete limited-edition model!
rscadd: Air rifle crate costs 25 credits and currently does not require clearance.
/:cl:
> Adds air rifle to the cargo list

- code/modules/reagents/reagent_dispenser.dm
Welderfuel tanks will no longer explode 100% of the time they're shot by something other than a practice laser or a lasertag beam.
* If `combustion` is true OR `damage` ≥ 20, the welderfuel tank **will explode.**
* If `combustion` is false AND `damage` > 20, the welderfuel tank **has a 10% chance to leak**.
* Welderfuel tank leaks send to admin logs.
* TODO TODO TODO: Add user-level notification that a welding fuel tank is leaking.
FIXES #61
> Welder tank hotfix

- code/modules/reagents/reagent_dispenser.dm
* Fixes a potential issue caused by a missing check. Welderfuel tanks will not be able to leak even more if it's already leaking if shot to the point of leakage.
* Adds a (FLW) jump button to admin log leak warning.
* Adds a feedback message for the user, if their bullet causes the welderfuel tank to leak.
CLOSES #64
CONTINUATION OF #63
> Day 1 welderfuel fix fixes

- code/modules/mob/living/carbon/human/examine.dm
* Should fix errors caused by functionally nonexistant proc being called when examining mobs, which means that Chatter's DreamDaemon console log should be cleaned up a bit.
> Frees the Daemon

- code/modules/mob/living/silicon/robot/examine.dm
* Fixes a runtime caused by a proc argument existing in `/atom/proc/examine` but not in `mob/living/examine`
* Adds borg name to their examine text.
* General code upkeep in code/modules/mob/living/silicon/robot/examine.dm for ease of legibility.
> Fixes borg examine text

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/carbon/human/emote_vr.dm
This is my next step up - its actually pretty complex and in the end I found myself getting rid of a lot of the code used by VORE Station. What I've done - in simple - Is added a system to snapping (I went ahead and replaced the flipping system, it doesn't really change anything other than the tweak of a value and trimming of un-needed code.) that will take a 1% value (or if you've somehow injured your hands, a 5% value) and will usually allow you to snap. Somehow if you hit that 1% (Or 5%) or are spamming like crazy, you'll break your hand (Or you'll simply lose it if you're a synth or a slime person.). Next you'll notice, if you compile the code, there is some lovely placeholder flavortext in there that ACTUALLY shows this time. 
If you've played long enough, you'll notice that the …
> HALF LIFE - FULL LIFE CONSEQUENCES I

- code/game/jobs/job_controller.dm
* Theoretically fixes an issue where a player that had their preferences on high before a whitelist came into effect could still randomly get a whitelisted job.
> Patch for a whitelist issue

- code/controllers/emergency_shuttle_controller.dm
- code/game/gamemodes/gameticker.dm
* Adds hostconsole feedback when a shift change starts, when the shuttle arrives at the station, and when the round ends properly.
* Adds a shift change horn to the station, as an extra bit of detail. It's on a variable and can be disabled.
* Adds a bit of feedback for the player when the server reboots for a new round.
Known issue: The horn may sound more than once if admin intervention causes the crew transfer shuttle to be called more than once. This issue should not come up during normal play, and as such no sanity checks for such an event have been added.
> End-of-round tweaks (POLL BEFORE COMMITTING)

- modular_aeiou/code/modules/projectiles/guns/projectile/shotgun_aeiou.dm
- modular_aeiou/code/modules/projectiles/projectile/reusable.dm
* Mangled BBs can now be recycled at an autolathe.
* Air rifles do more "damage" when hitting a target in the eye: The eye damage variable is unchanged, but it will blind the target and, if they're not already nearsighted, stunt their vision for a short time.
* Fixed description text, now notes you can reuse BBs
* Nerfs simpleanimal damage to 35
* Fixes Limited Edition examine text. The clock and compass now function properly.
CLOSES #80 AS FIXED
> Air rifle updates

- code/controllers/emergency_shuttle_controller.dm
* End-of-shift horn file and volume are now variables for easier adminbus.
* Shift horn is now turned into a proc, so admins can blow it whenever they want, for further adminbus.
* The end-of-shift horn will now only blow once without admin involvement; if the horn blows it disables it for the rest of the round.
> Tweaks to end-of-shift horn

- code/modules/mob/living/carbon/human/species/station/station_vr.dm
* Akula should now be able to speak Skrellian. Likewise, Zoren should now be able to speak Terminus.
* This is a bandage patch and should be fixed properly, later down the line.
CLOSES #85 AS PATCHED
> Patches Akula and Zorren language barriers

- code/modules/client/preference_setup/antagonism/02_candidacy.dm
* Patches an issue where antag selection was not available, even if the mode was compiled, by bypassing the compilation check.
***As the issue was unable to be reproduced locally, it was unable to be tested locally.***
CLOSES #100 AS PATCHED
Local test: "It compiles."
> Patch for antag selection issue

- modular_aeiou/code/modules/clothing/head/misc_aeiou.dm
This makes the various cold weather headgear actually work as cold weather headgear. Since the server has a frozen planet available to players it'd only make sense to add more options for warm hats
> Make cold weather hats coldworthy

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
On top of the named feature being coded in, other key edits in this PR are:
- The load_character() savefile proc (the one performing the reset) is cleaned up, and needless redundancies are removed.
- The confirmation dialog is moved into the load_character() proc and made descriptive to identify the slot you're wiping.
- The proc detects that the slot is already empty and lets you know. No sense deleting a directory that doesn't exist.
I am open to discussion if you guys have thoughts on this.
> "Reset slot" button now resets the slot, plus some tweaks.

- modular_aeiou/code/game/objects/items/weapons/crafted_weapons_aeiou.dm
I noticed the glass shiv wasn't embedding at all when I was testing it out, even though its embed_chance was set to 100. Poked my nose around and realized there's a formula involved that was apparently causing an overflow. With a bit more damage and giving it sharpness, it should now have a base 100% chance to embed on attack as originally intended.
> fixes the glass shiv so it now embeds on melee attack

- code/game/machinery/suit_storage_unit.dm
- code/modules/mining/machine_processing.dm
- code/modules/mob/living/autohiss.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/power/singularity/singularity.dm
A bundle of fixes for AEIOU. Some more details on the fixes:
* Resizes the lobby menu, suit cycler UI, and ore processor UI so you're not left with a window that's slightly too small with an unnecessary scrollbar. It was also annoying having to resize each time to use the machines quickly with the bottommost buttons.
* Auto-hiss no longer resets each time you lose connection. It's attached to the mob now instead of the client and should persist as long as the mob is in existence.
* Singularity grow/shrink messages between stages were backwards. A simple adjustment has been made to fix this. (Note: As it's currently coded, there is no way to invoke the proper message when the singularity drops from Super to Five. But that's a different issue and not the aim of this fix. You won't see that …
> Fixes UI window sizes, auto-hiss, and singulo messages: Take 2.

- code/game/machinery/suit_storage_unit.dm
- code/game/machinery/suit_storage_unit_vr.dm
A resubmission of the change I made last year, updated and code guidelines compliant.
The fix was originally just to include helmets inside suits, but I ended up rehauling a section of the proc to remove a lot of unnecessarily redundant lines of code. I didn't want to end up writing the same lines of code 16 times.
I used find/replace with regex on the switch structure to build the lookup tables around the names, to ensure accuracy and completeness.
As always, I'm open to discussion.
> Fixes suit cyclers ignoring helmets in suits and replaces bloated code.

- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/planet/sif.dm
This is a partial followup to #147 from when I observed how long you are stunned if you're holding an umbrella in a storm, but also to fix #134 where phase weapons are useless because of a commented block of code. Thank you @EvilJackCarver for figuring that out the first time and also for reminding me about it recently.
Phase weapons of all varieties (and the BB gun, for that matter) should now do their intended damage to mobs. Hurray for explorers and anyone else that needs to protect themselves from hostile fauna like ~~Ian~~ giant spiders and slightly angrier giant spiders and **really pissed off** giant spiders.
For whatever reason, the stun dealt to someone holding an umbrella is 20 seconds long. I have no idea why it is that long, I assume it has something to do with a conversion …
> making friends with umbrellas and phaseguns

- code/modules/planet/sif.dm
Uses the gender datum system that eliminates the need to settle for they/them/their/theirs in visible messages where src != usr. It's not the most user-friendly, and I had to look at examples to figure out how to use it correctly. When I feel up to it I may try to change that. Also, after conducting a search of all "var/datum/gender/*" declarations I noticed the convention appears to be "T" or "T?" for the gender var.
I'm long-winded in my PRs, I know.
> Amends #149 from Chatter42 to use gender datums in visible messages.

- code/modules/mob/living/living.dm
- code/modules/vehicles/vehicle.dm
The issue was caused by the fact that after the resist verb unbuckled you, you were still loaded to the tug. Teleporting was caused by the unload proc assuming you were still on the tug and force-moving you to a tile according to its decision process.
I also noticed that buckling to the tug displayed a message, while unbuckling didn't. I modified the code to call the proper proc that would display an unbuckle message.
> Fixes #132 and adds unbuckle message to vehicles.

- code/modules/mob/living/carbon/human/human_attackhand.dm
It appears the inactive hand immunity from disarms was merely a bug that's been around since April 2015. This PR fixes a typo that was present in the original edit to the code. Sorry in advance to everyone who's gotten used to exploiting the off-hand immunity.
> Fixes a typo, now including the inactive hand in disarms.

- code/modules/mob/living/silicon/robot/robot_vr.dm
Robot Nom is a verb every borg has, and it's different from a dogborg belly module.
> Removes Robot Nom verb.

- maps/southern_cross/southern_cross-3.dmm
The access problem with the suit cycler in the mining outpost originated from the fact that it was the generic type that contains all departments and can only be opened by the CD. After this change the cycler in the outpost will be the mining cycler, now able to be opened by miners.
No longer do miners who require a suit need to rely solely on the station-side cycler to refit their suits.
> Replaces suit cycler in mining outpost with mining subtype.

- maps/southern_cross/southern_cross_areas.dm
The names of the Faxälven and Indalsälven Rivers on the outpost level and the Svartån River in the wilderness are stored in UTF-8 format, but the game uses ISO and causes them to render incorrectly (e.g. "FaxÃ¤lven River"). I fixed the names, so they should render correctly now.
Note: GitHub appears to parse both UTF-8 and ISO, so it doesn't look like there's any change.
> Fixes three river names in outpost and wilderness maps.

- code/controllers/autotransfer.dm
Otherwise, it'll properly say this will be your FINAL extend vote.
> Fixed final vote message to say "ONLY" only if it's the only one.

- maps/southern_cross/southern_cross-3.dmm
:warning: Not to be confused with the SAR Prep Area; the first-aid station is in xenobio/xenoflora.
:wrench: Removes access restrictions from the first aid station on the outpost.
/:cl:
This should have been part of #190 but I forgot about this particular medical station.
> Removes access restrictions from Outpost First Aid Station.

- maps/southern_cross/shuttles/crew_shuttles.dm
➖ Removes 'Sif Orbit' from shuttle destination list.
🛠 Adjusts Shuttle 2 initial depart time to compensate.
🛠 Reduces autopilot on-pad dock time to 90 seconds, as that is the approximate duration of the journey.
/:cl:
https://www.youtube.com/watch?v=G7aHG-PFxOY for time demonstration.
CLOSES #192 AS FIXED
> Shuttles are now faster

- code/modules/mob/living/carbon/human/emote_vr.dm
➖ You can no longer awoo, weh, peep, nya, or mlem while muzzled.
/:cl:
> Fixes muzzles not stopping *awoo, etc.

- code/controllers/master.dm
- code/modules/admin/admin.dm
🛠 The "Start Now" admin verb will now only start the round if the initializations are complete (with a 1 second delay).
/:cl:
This is a draft for now (for Travis checks), gotta let it run and check stability when I get home.
CLOSES #197 AS FIXED
> Start Now only starts if the round is ready

- code/modules/busy_space/air_traffic.dm
🛠 Shuttle no longer thinks it's a space tram.
/:cl:
CLOSES #191 AS FIXED
> I like trains.

- code/controllers/autotransfer.dm
- code/controllers/configuration_eclipse.dm
- code/controllers/emergency_shuttle_controller.dm
- code/game/gamemodes/gameticker.dm
- code/game/jobs/job/captain.dm
- code/game/jobs/job/civilian.dm
- code/game/jobs/job/engineering.dm
- code/game/jobs/job/job_vr.dm
- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
- code/game/jobs/job/security.dm
- code/game/jobs/job/silicon.dm
- code/game/jobs/job/special.dm
- code/game/jobs/job_controller.dm
- code/game/jobs/whitelist_vr.dm
- config/example/config_eclipse.txt
- eclipsestation.dme
- modular_eclipse/code/modules/admin/verbs/totr.dm
- modular_eclipse/reginald/reginald.dm
➕ Adds an Eclipse-specific configuration file, to allow downstreams and devs to do their own stuff.
➕ Heads of Staff, Security, and Silicons are now whitelist-restricted or not based on config options.
🛠 Job-related whitelisting no longer restricts admin staff (defined as staff with the R_ADMIN right) from joining as a particular job, if it's enabled in the config options.
/:cl:
~~Untested, about to check it.~~ Tested as of latest commit review comment
> Adds an Eclipse-specific configuration file, tweaks whitelist checks

- code/controllers/configuration_eclipse.dm
- code/modules/mob/living/simple_animal/animals/mouse.dm
- config/example/config_eclipse.txt
➕ Mice now have a chance to chew wires. This behaviour can be enabled via the config.
⚠️ Config updated.
/:cl:
This should give engineers something to do.
>*That poor wire...*
---
* MICE_EAT_WIRES
* **Master enable**. If commented out, mice will not eat wires.
* MICE_WIRE_CHOMP_CHANCE *<int>* 
* Chance for a mouse to chew a wire, after it moves. 
* Units: percent
* Default: 5
* MICE_WIRE_COOLDOWN *<int>* 
* How long after a mouse chews through a wire can any other mouse (itself included, if it survived) chew through one. 
* Units: seconds
* Default: 600 (10 minutes)
* ROUNDSTART_MOUSE_WIRE_COOLDOWN
* If commented out, mice will be able to eat wires at roundstart. Otherwise, mice will wait `MICE_WIRE_COOLDOWN` seconds before they can chew a wire.
---
Call `debug_wire()` …
> Mice can now chew wires.

- code/modules/mob/living/simple_animal/animals/mouse.dm
**CAUTION: This PR has not been tested past a compile check.**
🛠 Tweak mouse wire-chewing behaviour. Mice now have a per-type probability, which means certain mouse types may be more likely in the future to chew the cables.
/:cl:
This is how /tg/ has it. I don't know why either.
Diff, omitting whitespace changes:
```diff
.../mob/living/simple_animal/animals/mouse.dm      | 76 ++++++++++++----------
1 file changed, 40 insertions(+), 36 deletions(-)
diff --git a/code/modules/mob/living/simple_animal/animals/mouse.dm b/code/modules/mob/living/simple_animal/animals/mouse.dm
index 904dde92de..8ecfd4bafd 100644
--- a/code/modules/mob/living/simple_animal/animals/mouse.dm
+++ b/code/modules/mob/living/simple_animal/animals/mouse.dm
@@ -42,6 +42,8 @@
meat_type = …
```
> Tweaks to mouse wire behaviour.

- code/_onclick/click_legacy.dm
Partial revert of `click.dm` from the Cit merge. Players can no longer grab things through cameras. Or from across the room.
A backup file, `click_legacy.dm`, is included in the event that the fix breaks horribly; this is a full revert and contains everything exactly as it was before the upstream merge. Using it will issue warnings on the precompiler and cause Travis to shit its fuck; the former is intended and the latter is an unfortunate side effect of using the `#warn` precompiler command.
> Removes telekinesis from the game.

- code/modules/busy_space/air_traffic.dm
For some reason, the change where I made this its own channel didn't commit. Which is weird, because I could have sworn that it worked in testing.
🔧 Fixes regional ATC chatter.
/:cl:
> Fixes regional ATC

- code/controllers/configuration_eclipse.dm
- code/controllers/subsystems/dispatcher_eclipse.dm
- code/game/jobs/job_controller.dm
- code/game/machinery/cryopod.dm
- code/game/machinery/requests_console.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/mob/dead/observer/free_vr.dm
- code/modules/research/message_server.dm
- config/example/config_eclipse.txt
- eclipsestation.dme
Going to go ahead and draft up a PR, so I can get everything ready and started for the NT DAD and stop cluttering up that one card. This is the plans and all that.
**This is part 1 of that.**
Adds framework for the NT Department Alarm Dispatcher. This framework will tie in to the current Request Console System's "request assistance" feature. This is intended to 
If a player requests assistance from a department AND the department does not have any players, the NT DAD should go to the Discord's role pings channel and ping the relevant group. If the player requests a department head, the NT DAD should act as if the department itself was pinged.
If the department requested has players, the request consoles should receive the message as normal, without a NT DAD ping.
I'll need to tie into the …
> NT Department Alarm Dispatcher - Phase 1

- code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
🔧 Fixes issues with wheelchair speed caused by malformed indentation.
⚠️ Known issue: Doors will initially reject a bump-open. 
⚠️ Known issue: Footsteps play if your character has feet. 
/:cl:
I have no intention of entirely rewriting wheelchair code to address the above two known issues at this time.
CLOSES #238 AS FIXED
> Fixes wheelchair speed

- .github/CODEOWNERS
- code/controllers/Processes/supply.dm
- code/game/objects/items/devices/radio/beacon.dm
- code/modules/maps/tg/map_template.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/simple_animal/animals/giant_spider.dm
- code/modules/organs/internal/brain.dm
- maps/submaps/surface_submaps/wilderness/wilderness.dm
- modular_eclipse/maps/submaps/surface_submaps/wilderness/wilderness.dm
Assorted fixes to the code, from what I can see on the `nt-dept-dispatcher` branch.
🔧 Adds more nullchecks to the supply crate ordering (#200)
🔧 Beacon sprites now function as intended (#243)
🔧 Brain surgery now shouldn't pull the person to the brain if the mind can't be cloned (#184)
🔧 Wilderness submap loader can now spawn more than one of some of Sif's deep-woods stuff. (#248)
🔧 Tweak to examine code. (#241)
🛠 Tweaks to Github tooling
➕ Adds a recharge mechanic to Taser spiders. It's in beta.
/:cl:
CLOSES #248 
CLOSES #243 AS FIXED
CLOSES #241 AS FIXED
CLOSES #200 AS FIXED
PATCHES #184 FOR BRAIN SURGERY, DOES NOT FIX MAIN ISSUE
> Assorted fixes

- code/game/antagonist/antagonist.dm
- code/game/gamemodes/game_mode.dm
- code/game/jobs/job_controller.dm
Nestor, I'll let you decide whether this gets through the code freeze as a "bugfix or critical patch", or if it falls afoul and is gonna need to wait til the freeze is over.
fix: Patches antag selection. Antag selection now has more checks that should prevent it from drafting protected rounds.
/:cl:
Can't really do much testing in dev without more people in my dev server, and I really don't feel up for that.
In cases where antag status is independent of job (e.g. traitor, changeling), job selection takes priority over antag selection still. This means there may come an issue where you will have an empty traitor round because the only guy that's got it enabled is security.
I'm posting what I have. I'm beat down and tired.
PAtches #264, does not entirely fix.
> Patch for antag selection
