code/modules/vore/fluffstuff/custom_items_vr_aeiou.dm, modular_aeiou/code/modules/client/preference_setup/loadout/loadout_general.dm
Turns many balls into one ball
=> condenses tennisball loadout

code/modules/power/lighting.dm
When a light flickers, it no longer makes a noise
=> Flickering lights dont make noises

modular_aeiou/code/modules/client/preference_setup/loadout/loadout_head.dm
=> Adds maid hats to loadout

code/game/objects/structures/flora/trees.dm, modular_aeiou/README.md, modular_aeiou/code/modules/mining/mine_items_aeiou.dm, vorestation.dme
Trees can now be chopped again. 
Work on the Heavy Duty Drill
=> Merge, drill and tree Fix

modular_aeiou/code/modules/projectiles/ammunition/magazines_aeiou.dm
=> teeny commit

modular_aeiou/code/modules/projectiles/guns/projectile/shotgun_aeiou.dm, modular_aeiou/code/modules/projectiles/projectile/reusable.dm
* Reduces ammo capacity to 60 rounds.
* Reduces theoretical average bullet reuse rate to 20%.
* It is the variable `drop_chance` for ease of modification later.
* Adds an itemtype under `obj/item/trash` so the mangled bullet that drops has an itemtype to go to.
=> Nerfs the air rifle.

code/game/objects/structures/flora/trees.dm, modular_aeiou/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-AEIOU.dm, modular_aeiou/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine_AEIOU.dm, modular_aeiou/code/modules/reagents/Chemistry-Recipes_AEIOU.dm
This new sap can be used to make a special chemical which converts oxy, brn brt damage into tox.
=> Adding a third reagents for trees. 

code/modules/mob/living/simple_animal/animals/cat.dm, code/modules/mob/living/simple_animal/animals/farm_animals.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Mobs include corgi and cat for now.
=> Add leather procs and to a few mobs.

code/game/mecha/combat/marauder.dm, code/game/mecha/combat/reticence.dm, code/game/mecha/equipment/tools/tools.dm, code/game/mecha/mecha.dm
Fixed the audio loop whenever you opened the menu.
=> Mech noises. This time BETTER.

modular_aeiou/code/game/objects/items/weapons/crafted_weapons_aeiou.dm, modular_aeiou/code/modules/mining/mine_items_aeiou.dm
Fixed a typo in the shiv. Made some more work for the drill modularity. I need to figure how to make them actually take values from the parts once installed.
=> Shivs and drill.

code/game/objects/items/stacks/sheets/leather.dm, code/modules/materials/material_recipes.dm, code/modules/mob/living/simple_animal/simple_animal.dm
I've added some basic recipes to the leather stuff and normally it should drop for all simple mobs.
=> Leather stuff

code/modules/projectiles/guns/projectile.dm
* No notable user-level changes.
=> Adds minor framework to allow concealment of remaining ammo from projectile-based weaponry's examine text.

code/_onclick/click.dm, code/game/machinery/alarm.dm, code/game/machinery/kitchen/microwave.dm, code/game/machinery/pipe/construction.dm, code/game/machinery/washing_machine.dm, code/game/objects/items/devices/flashlight.dm, code/modules/clothing/masks/breath.dm, code/modules/power/apc.dm
* Adds a bunch of alt-click shortcuts to various objects.
* **Air alarm/APC:** Toggle lock
* **Breath masks:** Adjust
* **Flashlight:** Cycle brightness forward
* **Microwave/Washing machine:** Start
* **Pipes:** Rotate clockwise
* Holding shift and pressing the middle mouse button will now cause you to point at something.
=> [READY] QoL improvements.

interface/skin.dmf
=> updated skin.dmf to have AEIOU instead of VORE

interface/skin.dmf
curse the autogenerated strings
=> Fixes mangled skin file

aeioustation.dme, modular_aeiou/code/modules/resleeving/machines.dm
Usability improvement for everyone, but also allows cyborgs to operate the resleeving room properly.
=> Enables click-drag insertion of patients into the resleeving pod

code/game/machinery/jukebox.dm, code/game/objects/structures/watercloset.dm, code/modules/vore/weight/fitness_machines_vr.dm, modular_aeiou/code/game/objects/items/weapons/material/sledgehammer_construction.dm, modular_aeiou/code/game/objects/items/weapons/tools.dm, modular_aeiou/code/modules/power/laser_centcom_aeiou.dm, modular_aeiou/code/modules/power/potato_aeiou.dm
- /obj/item/weapon/tool/wrench remplaces /obj/item/weapon/wrench
Those files weren't updated due to the fact we are a fork and shit.
=> Remplace old paths with up to date ones

modular_aeiou/code/modules/clothing/head/misc_aeiou.dm
Last PR I made didn't work, turned out I was missing something, but now I have it. This should work to make the Ushanka, Beanie, and Loose Beanie protect against the cold.
=> Make warm hats work, for real this time

modular_aeiou/maps/submaps/surface_submaps/wilderness/Hunted.dmm
I goofed when placing the tables in this PoI and it was throwing thirty or so runtime errors during map generation, this fixes that.
=> fixes runtimes with 'Hunted' PoI

code/modules/mob/new_player/login.dm
does what it says on the tin. very small change.
=> changes the name of the 'lobby screen'to 'AEIOU'

.github/CONTRIBUTING.md
=> Fixes CONTRIBUTING.md so the code of conduct link works.

.github/CONTRIBUTING.md
* Adds a recommended paragraph under Pull Requests.
* Removes a paragraph under Pull Requests that is now covered by the added paragraph.
* Rephrases a paragraph under Git Commit Messages.
This edit is open to discussion.
=> Edits the contribution guide where it addresses PR cleanliness.

modular_citadel/code/modules/clothing/head/misc_cit.dm
This removes code for cold resistant hats that both doesn't work and is redundant
=> Removes redundant cold hat code

code/__defines/admin_vr.dm, code/modules/admin/player_panel.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/admin/verbs/smite_vr.dm
* The two shadekin smites were removed from the vore smite list.
* The "FLW" option and a disconnected indicator were added to the new(er) player panel.
* A typo in the ahelp "IC Issue" message was fixed.
As always, I'm open to discussion.
=> Removes forbidden smites, adds stuff to PP, and fixes a typo.

code/world.dm
bugfix: Fixes a minor issue causing Travis checks to fail. No notable frontend changes.
/:cl:
=> Travis fix

code/modules/admin/player_panel.dm
My bad. I didn't test the player panel edit, and didn't see that my edit comment actually shows up in every player entry, or that the "FLW" button in the expanded section is moved down to the second line by a line break.
I fixed it and tweaked the disconnected indicator as well. It should be fine now.
=> Fixed an oops in the new player panel.

config/strings/sillytips.txt, config/strings/tips.txt
**This PR does not require a compile to push.**
🛠 Updates a few Tips of the Round to be appropriate for the Southern Cross. Adds a couple.
/:cl:
=> Updates Tips of the Round

.travis.yml
This reverts commit 9d084e580910b96babdef910237da92c6d936fb6.
=> Revert "Travis update"

eclipsestation.dme, modular_eclipse/code/modules/mob/living/carbon/human/species/station/traits/neutral.dm
Adds a new autohiss trait, that makes you sound like you're a hat in time seal character. And nothing else. 
Makes it easier to roleplay characters with functional amount of brain damage.
:cl:
add: added a new autohiss variety trait
/:cl:
=> Adds awootism autohiss trait.

.github/CODEOWNERS
**This PR affects GitHub only, and will not change anything in-game.**
GitHub will now auto-ping the relevant people for a review if their 'owned' code (as defined by the file this creates) is changed. This is a rudimentary setup, but can be expanded on later.
[More information can be found on GitHub's help page.](https://help.github.com/en/articles/about-code-owners)
=> Creates codeowner file

code/controllers/subsystems/dispatcher_debug.dm, code/modules/admin/admin_verbs.dm, eclipsestation.dme
PTrack system will dump to server logs if requested.
This is necessary for testing of player removal code
=> PTrack dump code

code/game/jobs/job/science.dm
:cl:
fix: fixed RD not being controlled by head whitelist
/:cl:
=> Fixes RD not being included into job whitelist

config/strings/tips.txt, eclipsestation.dme, modular_eclipse/code/modules/examine/descriptions/machines.dm
This adds a couple of sentences explaining a couple more ways to interact with the space heater, visible in the Examine tab to anyone looking at it. It also adds a new tip-of-the-round mentioning the cooling feature.
It helps to fill in a small gap in knowledge with the space heater. I personally didn't know the space heater could cool rooms down until someone else told me about it. It could easily happen with anyone else, and probably has.
:cl:
add: tip of the round: space heater can cool things
add: field of text explaining some additional interactions with the space heater
/:cl:
=> tiny tweaks involving the space heater
